name: RandomNick
main: Random\Main
version: 2.0.0
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: VMPE Development Team
commands:
  nick:
    description: "Nick yourself with a random nickname!"
    aliases: [n,nickname]
    permission: nick
    
permissions:
 nick:
  description: "Allow to give your a random nick"
  default: op
