name: RandomNick
main: Random\Main
version: 2.0.0-B2
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: UltimateDevs & Zeao
commands:
  vmnick:
    description: "Nick yourself with a random nickname!"
    permission: nick.nick
    
permissions:
 nick.nick:
  description: "Allow to give your a random nick"
  default: op
